>P1;1bina
structureX:1bin:   1 :A: 143 :A:leghemoglobin A:Glycine max:2.20:19.8
---------VAFTEKQDALVSSSFEAFKA--NIPQYSVVFYTSILEKAPA
AKDLFSFLA--N---GVDPTNPKLTGHAEKLFALVRDSAGQLKASGTVVA
D---AALGSVHAQK---AVTDPQFVVVKEALLKTIKAAVGD-KWSDELSR
AWEVAYDELAAAIKKA--------*
>P1;1lh1
structureX:1lh1:   1 : : 153 : :leghaemoglobin:Lupinus luteum: 2.00:27.3
---------GALTESQAALVKSSWEEFNA--NIPKHTHRFFILVLEIAPA
AKDLFSFLKGTS---EVPQNNPELQAHAGKVFKLVYEAAIQLEVTGVVVT
DATLKNLGSVHVSK---GVADAHFPVVKEAILKTIKEVVGA-KWSEELNS
AWTIAYDELAIVIKKEMDDAA---*
>P1;1hlm
structureX:1hlm:   1 : : 158 : :hemoglobin:Caudina (molpadia) arenicola:2.90:19.0
GATQSFQSVGDLTPAEKDLIRSTWDQLMT--HRTGFVADVFIRIFHNDPT
AQRKFPQMAGL--SPAELRTSRQMHAHAIRVSALMTTYIDEMDTE---VL
PELLATLTRTHDKN---HVGKKNYDLFGKVLMEAIKAELGV-GFTKQVHD
AWAKTFAIVQGVLITKHAS-----*
>P1;1hlb
structureX:1hlb:   1 : : 157 : :haemoglobin:Caudina arenicola: 2.50:15.0
GGTLAIQAQGDLTLAQKKIVRKTWHQLMR--NKTSFVTDVFIRIFAYDPS
AQNKFPQMAGM--SASQLRSSRQMQAHAIRVSSIMSEYVEELDSD---IL
PELLATLARTHDLN---KVGADHYNLFAKVLMEALQAELGS-DFNEKTRD
AWAKAFSVVQAVLLVKHG------*
>P1;2mm1
structureX:2mm1:   1 : : 153 : :myoglobin:Homo sapiens: 2.80:15.8
----------GLSDGEWQLVLNVWGKVEA--DIPGHGQEVLIRLFKGHPE
TLEKFDRFK-HLKSEDEMKASEDLKKHGATVLTALGGILKKKG-----HH
EAEIKPLAQSHATKH--KIPVKYLEFISEAIIQVLQSKHPG-DFGADAQG
AMNKALELFRKDMASNYKELGFQG*
>P1;1pmba
structureX:1pmb:   1 :A: 153 :A:myoglobin:Sus scrofa:2.50:18.5
----------GLSDGEWQLVLNVWGKVEA--DVAGHGQEVLIRLFKGHPE
TLEKFDKFK-HLKSEDEMKASEDLKKHGNTVLTALGGILKKKG-----HH
EAELTPLAQSHATKH--KIPVKYLEFISEAIIQVLQSKHPG-DFGADAQG
AMSKALELFRNDMAAKYKELGFQG*
>P1;1ymb
structureX:1ymb:   1 : : 153 : :myoglobin:Equus caballus: 1.90:15.5
----------GLSDGEWQQVLNVWGKVEA--DIAGHGQEVLIRLFTGHPE
TLEKFDKFK-HLKTEAEMKASEDLKKHGTVVLTALGGILKKKG-----HH
EAELKPLAQSHATKH--KIPIKYLEFISDAIIHVLHSKHPG-DFGADAQG
AMTKALELFRNDIAAKYKELGFQG*
>P1;1mbs
structureX:1mbs:   1 : : 153 : :myoglobin:Phoca vitulina: 2.50:26.8
----------GLSDGEWHLVLNVWGKVET--DLAGHGQEVLIRLFKSHPE
TLEKFDKFK-HLKSEDDMRRSEDLRKHGNTVLTALGGILKKKG-----HH
EAELKPLAQSHATKH--KIPIKYLEFISEAIIHVLHSKHPA-EFGADAQA
AMKKALELFRNDIAAKYKELGFHG*
>P1;1emy
structureX:1emy:   1 : : 153 : :myoglobin:Elephas maximus:1.78:15.3
----------GLSDGEWELVLKTWGKVEA--DIPGHGETVFVRLFTGHPE
TLEKFDKFK-HLKTEGEMKASEDLKKQGVTVLTALGGILKKKG-----HH
EAEIQPLAQSHATKH--KIPIKYLEFISDAIIHVLQSKHPA-EFGADAQG
AMKKALELFRNDIAAKYKELGFQG*
>P1;1lht
structureX:1lht:   1 : : 153 : :myoglobin:Caretta caretta:2.00:17.8
----------GLSDDEWNHVLGIWAKVEP--DLSAHGQEVIIRLFQLHPE
TQERFAKFK-NLTTIDALKSSEEVKKHGTTVLTALGRILKQKN-----NH
EQELKPLAESHATKH--KIPVKYLEFICEIIVKVIAEKHPS-DFGADSQA
AMKKALELFRNDMASKYKEFGFQG*
>P1;1myt
structureX:1myt:   5 : : 153 : :myoglobin:Thunnus albacares: 1.74:17.7
--------------ADFDAVLKCWGPVEA--DYTTMGGLVLTRLFKEHPE
TQKLFPKFA-GIA-QADIAGNAAISAHGATVLKKLGELLKAKG-----SH
AAILKPLANSHATKH--KIPINNFKLISEVLVKVMHEKA---GLDAGGQT
ALRNVMGIIIADLEANYKELGFSG*
>P1;2pghb
structureX:2pgh:   1 :B: 146 :B:hemoglobin:Sus scrofa:2.80:15.4
---------VHLSAEEKEAVLGLWGKV----NVDEVGGEALGRLLVVYPW
TQRFFESFG-DLSNADAVMGNPKVKAHGKKVLQSFSDGLKHLD-----NL
KGTFAKLSELHCDQL--HVDPENFRLLGNVIVVVLARRLGH-DFNPDVQA
AFQKVVAGVANALAHKYH------*
>P1;2hhbb
structureX:2hhb:   1 :B: 146 :B:hemoglobin:Homo sapiens:1.74:16.0
---------VHLTPEEKSAVTALWGKV----NVDEVGGEALGRLLVVYPW
TQRFFESFG-DLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLD-----NL
KGTFATLSELHCDKL--HVDPENFRLLGNVLVCVLAHHFGK-EFTPPVQA
AYQKVVAGVANALAHKYH------*
>P1;1hdab
structureX:1hda:   2 :B: 146 :B:hemoglobin:Bos taurus:2.20:19.3
----------MLTAEEKAAVTAFWGKV----KVDEVGGEALGRLLVVYPW
TQRFFESFG-DLSTADAVMNNPKVKAHGKKVLDSFSNGMKHLD-----DL
KGTFAALSELHCDKL--HVDPENFKLLGNVLVVVLARNFGK-EFTPVLQA
DFQKVVAGVANALAHRYH------*
>P1;2mhbb
structureX:2mhb:   1 :B: 146 :B:hemoglobin:Equus caballus:2.00:23.1
---------VQLSGEEKAAVLALWDKV----NEEEVGGEALGRLLVVYPW
TQRFFDSFG-DLSNPGAVMGNPKVKAHGKKVLHSFGEGVHHLD-----NL
KGTFAALSELHCDKL--HVDPENFRLLGNVLVVVLARHFGK-DFTPELQA
SYQKVVAGVANALAHKYH------*
>P1;1hdsb
structureX:1hds:   1 :B: 145 :B:hemoglobin:Odocoileus virginianus:1.98:25.0
----------MLTAEEKAAVTGFWGKV----DVDVVGAQALGRLLVVYPW
TQRFFQHFG-NLSSAGAVMNNPKVKAHGKRVLDAFTQGLKHLD-----DL
KGAFAQLSGLHCNKL--HVNPQNFRLLGNVLALVVARNFGG-QFTPNVQA
LFQKVVAGVANALAHKYH------*
>P1;1fdhg
structureX:1fdh:   1 :G: 146 :G:hemoglobin (fetal f=II=):Homo sapiens:2.50:31.9
---------GHFTEEDKATITSLWGKV----NVEDAGGETLGRLLVVYPW
TQRFFDSFG-NLSSASAIMGNPKVKAHGKKVLTSLGDAIKHLD-----DL
KGTFAQLSELHCDKL--HVDPENFKLLGNVLVTVLAIHFGK-EFTPEVQA
SWQKMVTGVASALSSRYH------*
>P1;1spgb
structureX:1spg:   1 :B: 147 :B:hemoglobin:Leiostomus xanthurus:1.95:19.1
---------VDWTDAERAAIKALWGKI----DVGEIGPQALSRLLIVYPW
TQRHFKGFG-NISTNAAILGNAKVAEHGKTVMGGLDRAVQNMD-----NI
KNVYKQLSIKHSEKI--HVDPDNFRLLGEIITMCVGAKFGPSAFTPEIHE
AWQKFLAVVVSALGRQYH------*
>P1;1hbhb
structureX:1hbh:   1 :B: 146 :B:hemoglobin:Pagothenia bernacchii:2.20:-1.00
---------VEWTDKERSIISDIFSHM----DYDDIGPKALSRCLIVYPW
TQRHFSGFG-NLYNAEAIIGNANVAAHGIKVLHGLDRGVKNMD-----NI
AATYADLSTLHSEKL--HVDPDNFKLLSDCITIVLAAKMGH-AFTAETQG
AFQKFLAVVVSALGKQYH------*
>P1;1outb
structureX:1out:   1 :B: 146 :B:hemoglobin I:Oncorhyncus mykiss:2.30:16.2
---------VEWTDAEKSTISAVWGKV----NIDEIGPLALARVLIVYPW
TQRYFGSFG-NVSTPAAIMGNPKVAAHGKVVCGALDKAVKNMG-----NI
LATYKSLSETHANKL--FVDPDNFRVLADVLTIVIAAKFGA-SFTPEIQA
TWQKFMKVVVAAMGSRYF------*
>P1;1spga
structureX:1spg:   1 :A: 143 :A:hemoglobin:Leiostomus xanthurus:1.95:19.1
----------SLSATDKARVKALWDKIEG--KSAELGAEALGRMLVSFPQ
TKIYFSEWGQDLG-----PQTPQVRNHGAVIMAAVGKAVKSID-----NL
VGGLSQLSELHAFKL--RVDPANFKILAHNIILVISMYFPG-DFTPEVHL
SVDKFLACLALALSEKYR------*
>P1;1pbxa
structureX:1pbx:   1 :A: 142 :A:hemoglobin:Pagothenia bernacchii:2.50:17.8
----------SLSDKDKAAVRALWSKIGK--SADAIGNDALSRMIVVYPQ
TKTYFSHWP-DVT-----PGSPHIKAHGKKVMGGIALAVSKID-----DL
KTGLMELSEQHAYKL--RVDPANFKILNHCILVVISTMFPK-EFTPEAHV
SLDKFLSGVALALAERYR------*
>P1;1hdaa
structureX:1hda:   1 :A: 141 :A:hemoglobin:Bos taurus:2.20:19.3
----------VLSAADKGNVKAAWGKVGG--HAAEYGAEALERMFLSFPT
TKTYFPHF--DLS-----HGSAQVKGHGAKVAAALTKAVEHLD-----DL
PGALSELSDLHAHKL--RVDPVNFKLLSHSLLVTLASHLPS-DFTPAVHA
SLDKFLANVSTVLTSKYR------*
>P1;2hhba
structureX:2hhb:   1 :A: 141 :A:hemoglobin:Homo sapiens:1.74:16.0
----------VLSPADKTNVKAAWGKVGA--HAGEYGAEALERMFLSFPT
TKTYFPHF--DLS-----HGSAQVKGHGKKVADALTNAVAHVD-----DM
PNALSALSDLHAHKL--RVDPVNFKLLSHCLLVTLAAHLPA-EFTPAVHA
SLDKFLASVSTVLTSKYR------*
>P1;2mhba
structureX:2mhb:   1 :A: 141 :A:hemoglobin:Equus caballus:2.00:23.1
----------VLSAADKTNVKAAWSKVGG--HAGEYGAEALERMFLGFPT
TKTYFPHF--DLS-----HGSAQVKAHGKKVGDALTLAVGHLD-----DL
PGALSDLSNLHAHKL--RVDPVNFKLLSHCLLSTLAVHLPN-DFTPAVHA
SLDKFLSSVSTVLTSKYR------*
>P1;2pgha
structureX:2pgh:   1 :A: 141 :A:hemoglobin:Sus scrofa:2.80:15.4
----------VLSAADKANVKAAWGKVGG--QAGAHGAEALERMFLGFPT
TKTYFPHF--NLS-----HGSDQVKAHGQKVADALTKAVGHLD-----DL
PGALSALSDLHAHKL--RVDPVNFKLLSHCLLVTLAAHHPD-DFNPSVHA
SLDKFLANVSTVLTSKYR------*
>P1;1hdsa
structureX:1hds:   1 :A: 141 :A:hemoglobin (sickle cell):Odocoileus virginianus:1.98:25.0
----------VLSAANKSNVKAAWGKVGG--NAPAYGAQALQRMFLSFPT
TKTYFPHF--DLS-----HGSAQQKAHGQKVANALTKAQGHLN-----DL
PGTLSNLSNLHAHKL--RVNPVNFKLLSHSLLVTLASHLPT-NFTPAVHA
NLNKFLANDSTVLTSKYR------*
>P1;1outa
structureX:1out:   1 :A: 142 :A:hemoglobin I:Oncorhyncus mykiss:2.30:16.2
----------SLTAKDKSVVKAFWGKISG--KADVVGAEALGRMLTAYPQ
TKTYFSHWA-DLS-----PGSGPVKKHGGIIMGAIGKAVGLMD-----DL
VGGMSALSDLHAFKL--RVDPGNFKILSHNILVTLAIHFPS-DFTPEVHI
AVDKFLAAVSAALADKYR------*
>P1;2lhb
structureX:2lhb:   1 : : 149 : :haemoglobin:Petromyzon marinus: 2.00:14.2
-PIVDTGSVAPLSAAEKTKIRSAWAPVYS--TYETSGVDILVKFFTSTPA
AQEFFPKFKG-LTTADELKKSADVRWHAERIINAVDDAVASMD--DTEKM
SMKLRNLSGKHAKSF--QVDPEYFKVLAAVIADTVAA----------GDA
GFEKLMSMICILLRSAY-------*
>P1;2hbg
structureX:2hbg:   1 : : 147 : :haemoglobin:Glycera dibranchiata: 1.50:12.7
----------GLSAAQRQVIAATWKDIAGADNGAGVGKKCLIKFLSAHPQ
MAAVF-GFS--------GASDPGVAALGAKVLAQIGVAVSHLG--DEGKM
VAQMKAVGVRHKGYGNKHIKAQYFEPLGASLLSAMEHRIGG-KMNAAAKD
AWAAAYADISGALISGLQS-----*
>P1;3sdha
structureX:3sdh:   2 :A: 146 :A:hemoglobin I:Scapharca inaequivalvis:1.40:15.9
---SVYDAAAQLTADVKKDLRDSWKVIGS--DKKGNGVALMTTLFADNQE
TIGYFKRLG----NVSQGMANDKLRGHSITLMYALQNFIDQLD--NPDDL
VCVVEKFAVNHITR---KISAAEFGKINGPIKKVLASKN----FGDKYAN
AWAKLVAVVQAAL-----------*
>P1;1mba
structureX:1mba:   1 : : 146 : :myoglobin:Aplysia liminacia: 1.60:19.3
----------SLSAAEADLAGKSWAPVFA--NKNANGLDFLVALFEKFPD
SANFFADFKG--KSVADIKASPKLRDVSSRIFTRLNEFVNNAA--NAGKM
SAMLSQFAKEHVGF---GVGSAQFENVRSMFPGFVASVA---APPAGADA
AWTKLFGLIIDALKAAGA------*
>P1;1itha
structureX:1ith:   1 :A: 141 :A:hemoglobin:Urechis caupo:2.50:14.7
----------GLTAAQIKAIQDHWFLNIKG-CLQAAADSIFFKYLTAYPG
DLAFFHKFSSV--PLYGLRSNPAYKAQTLTVINYLDKVVDALG----GNA
GALMKAKVPSHDAM---GITPKHFGQLLKLVGGVFQEEFS---ADPTTVA
AWGDAAGVLVAAMK----------*
>P1;1ecd
structureX:1ecd:   1 : : 136 : :erythrocruorin:Chironomous thummi thummi: 1.40:19.0
-----------LSADQISTVQASFDKVKG------DPVGILYAVFKADPS
IMAKFTQFAG--KDLESIKGTAPFETHANRIVGFFSKIIGELP-----NI
EADVNTFVASHKPR---GVTHDQLNNFRAGFVSYMKAHT---DFA-GAEA
AWGATLDTFFGMIFSKM-------*
>P1;1a4fa
structureX:1a4f:   1 :A: 141 :A: hemoglobin alpha-a chain: Anser indicus: 2.00: 19.8
----------VLSAADKTNVKGVFSKISG--HAEEYGAETLERMFTAYPQ
TKTYFPHF--DLQ-----HGSAQIKAHGKKVVAALVEAVNHID-----DI
AGALSKLSDLHAQKL--RVDPVNFKFLGHCFLVVVAIHHPS-ALTAEVHA
SLDKFLCAVGTVLTAKYR------*
>P1;1a4fb
structureX:1a4f:   1 :B: 146 :B: hemoglobin beta chain: Anser indicus: 2.00: 19.8
---------VHWSAEEKQLITGLWGKV----NVADCGAEALARLLIVYPW
TQRFFSSFG-NLSSPTAILGNPMVRAHGKKVLTSFGDAVKNLD-----NI
KNTFAQLSELHCDKL--HVDPENFRLLGDILIIVLAAHFAK-EFTPDCQA
AWQKLVRVVAHALARKYH------*
>P1;1a9we
structureX:1a9w:   1 :E: 145 :E:hemoglobin epsilon chain:Homo sapiens: 2.90: 18.5
---------VHFTAEEKAAVTSLWSKM----NVEEAGGEALGRLLVVYPW
TQRFFDSFG-NLSSPSAILGNPKVKAHGKKVLTSFGDAIKNMD-----NL
KPAFAKLSELHCDKL--HVDPENFKLLGNVMVIILATHFGK-EFTPEVQA
AWQKLVSAVAIALAHKY-------*
>P1;1hbra
structureX:1hbr:   1 :A: 141 :A:hemoglobin alpha-d chain:Gallus gallus: 2.30: 22.2
----------MLTAEDKKLIQQAWEKAAS--HQEEFGAEALTRMFTTYPQ
TKTYFPHF--DLS-----PGSDQVRGHGKKVLGALGNAVKNVD-----NL
SQAMAELSNLHAYNL--RVDPVNFKLLSQCIQVVLAVHMGK-DYTPEVHA
AFDKFLSAVSAVLAEKYR------*
>P1;1a6m
structureX:1a6m:   1 : : 151 : :myoglobin:Physeter catodon: 1.00: -1
----------VLSEGEWQLVLHVWAKVEA--DVAGHGQDILIRLFKSHPE
TLEKFDRFK-HLKTEAEMKASEDLKKHGVTVLTALGAILKKKG-----HH
EAELKPLAQSHATKH--KIPIKYLEFISEAIIHVLHSRHPG-DFGADAQG
AMNKALELFRKDIAAKYKELGY--*
>P1;1cg5a
structureX:1cg5:   1 :A: 141 :A:hemoglobin:Dasyatis akajei: 1.60: 19.1
----------VLSSQNKKAIEELGNLIKA--NAEAWGADALARLFELHPQ
TKTYFSKFS-GFE-----ACNEQVKKHGKRVMNALADATHHLD-----NL
HLHLEDLARKHGENL--LVDPHNFHLFADCIVVTLAVNLQ--AFTPVTHC
AVDKFLELVAYELSSCYR------*
>P1;1cg5b
structureX:1cg5:   1 :B: 141 :B:hemoglobin:Dasyatis akajei: 1.60: 19.1
---------VKLSEDQEHYIKGVWKDV----DHKQITAKALERVFVVYPW
TTRLFSKLQGLFS-----ANDIGVQQHADKVQRALGEAIDDLK-----KV
EINFQNLSGKHQEI---GVDTQNFKLLGQTFMVELALHYKK-TFRPKEHA
AAYKFFRLVAEALSSNYH------*
